include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    unused_import: ignore
    unnecessary_null_comparison: ignore
    library_private_types_in_public_api: ignore
    use_key_in_widget_constructors: ignore
    prefer_final_fields: ignore
    curly_braces_in_flow_control_structures: ignore
    avoid_web_libraries_in_flutter: ignore
    unreachable_switch_default: ignore
