name: app_coldman_sa
description: "Aplicación Gestión de Modelo de negocio de climatización."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  numberpicker: ^2.1.2
  file_picker: ^10.1.9
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.2
  flutter_map: ^8.1.1
  http: ^1.4.0
  provider: ^6.1.5
  latlong2: ^0.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/